openshift/cluster-kube-controller-manager-operator

cmd/cluster-kube-controller-manager-operator/main.go
cmd/cluster-kube-controller-manager-operator/render/config.go
cmd/cluster-kube-controller-manager-operator/render/render.go
manifests/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
manifests/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml

This belongs to scheduler operator, but we can't wait for it now and we need to pass the bootstrapping. Logically this is closer to controller-manager than API server.
The scheduler have hardcoded config path, @sttts I guess we will need some config that will work :)
Also adds `--skip-scheduler` flag to render (in case we want to switch this off, like when scheduler operator will provide its bootstrap manifest)

add scheduler manifest

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/config/config-overrides.yaml
bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

This uses a deprecated flag (we'll need to fix that) to override the server being used by the daemonset controller manager.

don't use hostnetwork in daemonset

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/config/config-overrides.yaml
bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

We need to simplify the rendered config to be compatible with non-old cluster-up clusters.

make render produce minimal running config for later customization

---

bindata/bootkube/manifests/fake-checkpointer-daemonset.yaml
bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml

This is what we need to trick bootkube start and finish the phase 1, so bootkube will tear down the static pods and release the locks for daemonsets.
/cc @sttts 
/cc @deads2k

add fake scheduler and checkpointer to pass bootkube start

---

manifests/00_clusterkubecontrollermanageroperator_01_config.crd.yaml
manifests/00_clusterkubecontrollermanageroperator_02_config.yaml

discovery restmapper fails to resolve this mismatch in name and kind.
```go
func gvkToGVR(gvk schema.GroupVersionKind, restMapper *restmapper.DeferredDiscoveryRESTMapper) (*schema.GroupVersionResource, bool, error) {
mapping, err := restMapper.RESTMapping(gvk.GroupKind(), gvk.Version)
if err != nil {
return nil, false, fmt.Errorf("failed to get the resource REST mapping for GroupVersionKind(%s): %v", gvk.String(), err)
}
return &mapping.Resource, mapping.Scope.Name() == meta.RESTScopeNameNamespace, nil
}
```

fix: kinds for controllermanageroperatorconfig

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/bootkube/manifests/fake-kube-scheduler-deployment.yaml
bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml
cmd/cluster-kube-controller-manager-operator/render/config.go
cmd/cluster-kube-controller-manager-operator/render/render.go

This add locking mechanism similar to what API server using to prevent the host port conflicts. For cluster up the controller manager has to use the hostNetwork otherwise the connection to API server will fail and the pods created by daemonsets will keep hanging. With this I can get the controller manager operating.
/cc @deads2k 
/cc @sttts 
/cc @openshift/sig-master

add locking to prevent host port conflicts

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/bootkube/manifests/kube-controller-manager-daemonset.yaml

This also force controller manager daemonset to run on hostNetwork and use the localhost to reach out to API server. With this change I can see the controller manager successfully establishing connection to API server and running the controllers.
/cc @soltysh

fix selinux errors in lock dirs

---

manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml

This is causing issue in CVO when reading the manifest
```console
error parsing 0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml: error parsing:
error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
```

manifests: fix invalid yaml

---

cmd/cluster-kube-controller-manager-operator/render/render.go

For kube controller manager, we use hyperkube, not hypershift.
/cc @sttts

fix wrong image used by render

---

cmd/cluster-kube-controller-manager-operator/render/render.go

This is version  of https://github.com/openshift/cluster-kube-apiserver-operator/pull/69 where we don't remove the flag that is currently being used by installer but just mark it deprecated and hide it.
We can remove the flag once we fix the installer, but for now it will break the bootstrap.sh script installer use and will prevent this PR from merging.
We can revert the last commit when the installer move forward.
/cc @sttts

render: pluralize --config-overrides-file

---

bindata/bootkube/manifests/configmap-kube-controller-manager-config.yaml
bindata/v3.11.0/kube-controller-manager/cm.yaml
bindata/v3.11.0/kube-controller-manager/deployment.yaml
pkg/operator/v311_00_assets/bindata.go

There was a name mismatch before this PR.
Also we don't use the config created by the render command in the openshift-kube-controller-manager namespace.

Fix kube-controller-manager-config name

---

pkg/operator/observe_config.go
pkg/operator/observe_config_test.go
pkg/operator/starter.go

Fixes https://github.com/openshift/installer/issues/577.
Related to https://github.com/openshift/installer/issues/530.

Wire cloud-provider to kube-controller-manager

---

Makefile
README.md
hack/lib/Dockerfile-origin-release

Instead use the very same cluster-kube-apiserver-operator target:
```
$ IMAGE_REPOSITORY_NAME=sttts make images
$ docker push sttts/origin-cluster-kube-controller-manager-operator
$ cd ../cluster-kube-apiserver-operator
$ IMAGES=cluster-kube-controller-manager-operator IMAGE_REPOSITORY_NAME=sttts make origin-release
$ docker push sttts/origin-release:latest
```

Makefile: remove origin-release target

---

manifests/0000_12_cluster-kube-controller-manager-operator_00_namespace.yaml
manifests/0000_12_cluster-kube-controller-manager-operator_03_configmap.yaml
manifests/0000_12_cluster-kube-controller-manager-operator_04_clusterrolebinding.yaml
manifests/0000_12_cluster-kube-controller-manager-operator_05_serviceaccount.yaml
manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
pkg/operator/starter.go

Moves our namespace to openshift-cluster-kube-controller-manager-operator and updates our ClusterOperator to match.
/assign @sanchezl

move to operator specific namespace

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

"crictl ps -a" does not show pod names. So during disaster recovery full names for the containers is helpful.

Use kube-controller-manager as container name for easier debugging

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

@aveshagarwal asking here... if this is a static pod with nodeSelector filled in to pin it into specific master node, will the pod priority make any difference? (i don't think we use scheduler to schedule these, right?)
/cc @smarterclayton

make static pods node critical priority

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

One in a series of PRs to set memory requests for all control plane and high memory use components.
We are encountering master instability (https://github.com/openshift/installer/pull/408 https://github.com/openshift/installer/pull/785) as the number of components increase because many components run `BestEffort` giving the scheduler no information on pod resource usage.
On a steady state empty cluster, `kube-controller-manager` uses 143MB.
{pod_name="openshift-kube-controller-manager-dev-master-0"} | 142659584
Because it is a control plane component, I'm giving it a buffer and setting to `200Mi`
@deads2k @sttts  @derekwaynecarr

add memory request to kube-controller-manager and operator pod

---

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

This enables the HPA as we have resource metrics API now enabled
due to the addition of k8s prometheus adapter.
xref https://github.com/openshift/cluster-monitoring-operator/pull/174
I am not sure if there is more to set up to make HPA work in the openshift controller manager setup.
cc @brancz @sttts @squat @metalmatze

defaultconfig: enable horizontal pod autoscaler

---

bindata/bootkube/manifests/configmap-kube-controller-manager-client-ca.yaml

https://github.com/openshift/cluster-kube-controller-manager-operator/pull/110 caused cluster monitoring to break since the kube-ca intermediate is no longer loaded. Until we can ensure that across the board server certificates are distributed with their intermediate signer, we should include it in the ca bundle.
Re: https://jira.coreos.com/browse/MON-498
/cc @s-urbaniak @openshift/sig-auth @abhinavdahiya

Include kube-ca in client-ca bundle

---

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go

After https://github.com/openshift/installer/pull/982 was merged BYOR installs use `platform: none`. Our install waits for all CVO operators to complete successfully, but kube-controller-manager-operator fails with this setup:
```
- apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
creationTimestamp: '2019-01-08T16:39:29Z'
generation: 1
name: openshift-kube-controller-manager-operator
namespace: ''
resourceVersion: '10227'
selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-kube-controller-manager-operator
uid: f80027da-1363-11e9-85a4-42010af00002
spec: {}
status:
conditions:
- lastTransitionTime: '2019-01-08T16:49:28Z'
message: 'ConfigObservationFailing: configmap/cluster-config-v1.kube-system: no recognized cloud provider platform found: …
```

Support "none" cloudprovider

---

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1667606
Note to reviewers - I could not validate this fix in my local libvirt cluster. I suspect:
```
OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=docker.io/gnufied/origin-release:latest bin/openshift-install cluster ...
```
does not work correctly.

Update flexvolume location

---

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go

OpenStack's cloud provider is not being enabled at this point because we
haven't figured out a good way to upload its configs to the master
nodes.
This patch disables the openstack cloud provider for the kube
controllers.

openstack: Don't observe the openstack CP configs

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
bindata/v3.11.0/kube-controller-manager/pod.yaml
bindata/v3.11.0/kube-controller-manager/svc.yaml
pkg/operator/v311_00_assets/bindata.go

@deads2k @sttts lets discuss the probes under this PR...
Right now, we have wrong port on the service and I don't think so we serving the healthz or metrics security from controller manager. Also the `10252` seems odd and we need to decide if we keep it or just move to something else? (8444 before).

add liveness and readiness probes to static pod

---

pkg/operator/starter.go

this cert is created by the service-ca controller, which doesn't come up until after we are available. this piece of config must be optional.  I think this is flaky because the bootstrap controller manager can sometimes start the service-ca in time.
@smarterclayton 

make serving-cert optional

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

We need to avoid removing the old certs we have from above.
/assign @sjenning

fix the csr-signer-ca bundle to keep history

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/config/config-overrides.yaml

This matches what we use from the "real" `sa/ca.rt`.
/assign @sttts @mrogers950

switch to kube-ca as the starting ca.crt

---

pkg/operator/starter.go

embarrassing oversight.  Must have fallen out in one of the many rebases.

use versionRecorder when writing versions

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1666635
When operator management state is set to unknown value (because we miss the CR validation), the target controller should not keep managing but emit warning and do nothing.

targetconfigcontroller: emit warning when management state is set to unknown value

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go

We need https://github.com/openshift/installer/pull/1253 to support this transition.
In addition to changing the pod names, this also add revision suffix into pod container name, so it is clear in artifacts which revision the collected logs belonged to.
/hold

operator: remove openshift prefix from pod name

---

bindata/bootkube/manifests/configmap-initial-kube-controller-manager-csr-ca.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

I think https://github.com/openshift/cluster-kube-apiserver-operator/pull/296 is blocked on not having the expected trust in the csr-controller-ca resulting in an inability to speak to the master kubelets.

add all valid signers to csr-controller-ca

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/interfaces.go
pkg/operator/configobservation/serviceca/observeserviceca.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/starter.go

🐛  Bug 1668825: serviceaccounttoken/service-ca.crt is missing
**Cause:** Missing feature to sync service-ca CA bundle to kube-controller-manager
**Consequence:** In 3.x, the service CA bundle for validating cluster-created
serving certificates was automatically mounted into pods via the ServiceAccount
token secret volume. Workloads that rely upon the service-ca.crt being present
would break in 4.0.
**Fix:** Sync the service CA bundle from the serving-cert-signer to the
kube-controller-manager where it can be injected into serviceaccount token
secrets at admission. The CA bundle will be provided by the service-ca-operator
in a configmap in the "openshift-config-managed" namespace. From there, the
cluster-kube-controller-manager-operator is responsible syncing it to the …

feat(targetconfigcontroller): include service-ca bundle in server account CA bundle

---

pkg/cmd/resourcegraph/resourcegraph.go

We've moved to the new namespace with https://github.com/openshift/service-ca-operator/pull/29
@openshift/sig-auth @deads2k

update service-ca controller namespace

---

manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml

specifies system-cluster-critical priority for operator.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217

manifests: system-cluster-critical priority for operator

---

pkg/cmd/render/render.go
pkg/cmd/render/render_test.go

Fix https://jira.coreos.com/browse/CLOUD-357
Remove dependency with cluster api cluster object:
- discoverIPs from network config
- fallback to discover from cluster api object
Analogous to https://github.com/openshift/cluster-kube-apiserver-operator/pull/351
Then we can merge openshift/installer#1449
Then we can remove the fallback to discover from cluster api object

Remove cluster api dependency

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v311_00_assets/bindata.go

pod.yaml: add init container waiting for free port

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

We are not generating serving certs and we do not tolerate not having these certs, so this disables it until we sort out what to do.  This is why the KCM is dying in the rebase.

disable kcm secure serving

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

Rebase landed, we should switch the port to secure again. This updates controller manager default config and set the insecure port to 0 and also update the init container to check the secure port.
Also sets the `cert-dir` to `/var/run/kubernetes`.

switch controller manager to secure port

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

Rebase of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/199
This enabled delegated authentication.

specify kubeconfig for delegated authn and authz

---

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

@mfojtik @enxebre @derekwaynecarr 
We should not be changing ` node-monitor-grace-period` and `pod-eviction-timeout` from the defaults without cause and there is no cause provided.

bindata: use default node controller settings

---

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
pkg/operator/starter.go

This PR still depends on https://github.com/openshift/installer/pull/1516 for actual `Infrastructure` object to be populated. 
cc @deads2k

Sync cloudprovider configmap

---

bindata/v3.11.0/kube-controller-manager/pod.yaml
pkg/operator/v311_00_assets/bindata.go

Just an oversight when init containers were added

show logs in pod status

---

bindata/v3.11.0/kube-controller-manager/kubeconfig-cert-syncer.yaml
bindata/v3.11.0/kube-controller-manager/pod.yaml
cmd/cluster-kube-controller-manager-operator/main.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v311_00_assets/bindata.go

This explicitly sets args to the KCM based on operator managed ca bundles.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698672

explicitly set client-ca and aggregator-client-ca to avoid early fatal contact with unready KAS

---

manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml

for upgrades, we need to have deployment strategy recreate on our operators in case they are ever scaled.  We don't want to ever get a lease for new and later get a lease for old.
We need a distinct operator container to make install-gather happy at the moment.
@openshift/sig-master

update deployment for upgrade and install-gather

---

bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
bindata/bootkube/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
bindata/v3.11.0/kube-controller-manager/ns.yaml
manifests/0000_12_kube-controller-manager-operator_00_namespace.yaml
pkg/operator/v311_00_assets/bindata.go

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml

Avoid operator switching this back to normal. Also make it consistent with kube apiserver operator.

manifests: bump loglevel of operator to normal

---

manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml

As of now, because of infinite tolerations against all the possible taints, we are seeing that operators are not getting evicted from nodes that have NoExecute taint on them. This PR tightens the conditions around which can be pods can be scheduled/evicted. The downside is there is a very good chance that pods would be evicted from nodes that have certain conditions like disk-pressure, memory-pressure, taints added by other controllers(operators) etc. So, please make sure that this change is ok with your operator/operand before merging this PR.
/cc @sjenning @smarterclayton

Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down

---

pkg/operator/starter.go

/hold
I want to explore the idea of time conditions on resource-sync.
/assign @enj

prevent cert failures when tuning rotation down in CI

---

bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
bindata/v3.11.0/kube-controller-manager/ns.yaml
pkg/operator/v311_00_assets/bindata.go

Currently `openshift.io/cluster-monitoring` is applied as an annotation,
it should be a label.
Currently, in a freshly deployed cluster I don't even see the annotation applied though at all. The piece of code that does that (I believe) is here: https://github.com/openshift/cluster-kube-controller-manager-operator/blob/f3b13ef52ab480675cb6a665c1b4746a187db7d7/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L134
Let's see if labels get propagated successfully.
/assign @soltysh @mfojtik

bindata/kube-controller-manager: fix cluster-monitoring label

---

manifests/0000_25_kube-controller-manager-operator_01_config.crd.yaml
manifests/0000_25_kube-controller-manager-operator_01_config.crd.yaml-merge-patch

it was removed in https://github.com/openshift/cluster-kube-controller-manager-operator/commit/ec46b3e62d77e12ae80f2d3c0467707e22c5dac8#diff-e9fad36abe07802cd4c4d9e1cc7c0cc1

brings back managementState field validation

---

bindata/v4.1.0/kube-controller-manager/defaultconfig.yaml
pkg/operator/starter.go
pkg/operator/v411_00_assets/bindata.go

Wiring a cert-syncer to https://github.com/openshift/origin/pull/23717 so that it's updated regardless of whether the operator is running and it can work without a rollout.

wire CSR signer to a cert-synced certificates for update

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/interfaces.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

This builds on top of #284 but fixes wrong yaml import which was causing the error pointed out by Standa and modifies the configmap merging. 
/assign @deads2k @stlaz

add non-MITM proxy support

---

bindata/v4.1.0/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

This PR adds role and rolebinding necessary for creating lease leader lock during upgrades from 4.2 -> 4.3, with split of quota and security controllers from openshift-controller-manager to cluster-policy-controller.  
* PR to remove role/rolebinding from cluster-openshift-controller-manager-operator: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/125
* this blocks https://github.com/openshift/openshift-controller-manager/pull/37
@deads2k

move rbac for cluster-policy-controller leader lock to kcm-o

---

pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

`oc -n openshift-kube-controller-manager get secrets csr-signer -oyaml` is based on `oc -n openshift-kube-controller-manager-operator get secrets  -oyaml csr-signer` (notice the different namespaces).  This makes sense because the operator has do some pre-processing.  The targetconfigcontroller which produces the kcm secret from the kcmo secret didn't have a watch on kcmo secrets.  This means that when the kcmo secrets are deleted and recreated, the kcm secret is not guaranteed to be updated.  This can result in the kcm using an old csr-signer, which results in cluster death.

watch for changes to input secrets from the operator namespace

---

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
manifests/0000_90_kube-controller-manager-operator_05_alert-kcm-down.yaml
manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
pkg/version/version.go

* First commit will make service monitor secure and split the alerts to separate files (lists are evil in CVO)
* Second commit will fix collection of operator version metrics

Fix metrics

---

bindata/v4.1.0/kube-controller-manager/default-cluster-policy-controller-config.yaml
pkg/operator/v411_00_assets/bindata.go

cluster-policy-controller is crashing during bootstrap when trying to open the tls.crt file in 4.4:
```
F1113 14:28:52.501846       1 standalone_apiserver.go:119] open /etc/kubernetes/static-pod-resources/serving-cert/tls.crt: no such file or directory
```
The kube-controller-manager uses /etc/kubernetes/static-pod-resources/secrets/serving-cert/tls.crt
while the cluter-policy-controller is using /etc/kubernetes/static-pod-resources/serving-cert/tls.crt (without the `/secrets/`).
This should fix issue by updating the path the cluster-policy-controller
is using to the correct location containing the TLS asssets.
/hold @deads2k said this could be a proper bug that needs fixing so putting a
hold in case we need to update the title, do cherry-picks, etc.

pkg,bindata: Update path to cluster-policy-controller service serving certificate and private key

---

manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
manifests/0000_90_kube-controller-manager-operator_05_alert-kcm-down.yaml
manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml
bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go
test/e2e/operator_test.go

This is a work in progress, trying to create a simple e2e that deletes the KCM configmap then attempts to create a replicaset to see if KCM recovered from the deletion, as described here: https://bugzilla.redhat.com/show_bug.cgi?id=1744984

Bug 1744984: Add e2e test for kube controller manager lease configmap deletion

---

bindata/v4.1.0/kube-controller-manager/default-cluster-policy-controller-config.yaml
pkg/operator/v411_00_assets/bindata.go

If you say `net.Listen("tcp", "0.0.0.0:10357")`, golang will actually create a dual-stack IPv4/IPv6 listening socket. But for historical reasons (having to do with bad IPv6 compat in older kube I think), we default to passing `"tcp4"` (the default value of `configv1.ServingInfo.BindNetwork`) instead of `"tcp"`, forcing IPv4-only.
There is no reason these days for servers on the pod network to enforce IPv4-only, so this overrides the default for kube-controller-manager.
This will need to be backported to 4.3.
(based on an earlier patch from @russellb )

Specify "bindNetwork: tcp" so controller manager will work on IPv6 single-stack

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
bindata/v4.1.0/kube-controller-manager/trusted-ca-cm.yaml
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

This was done based on https://github.com/openshift/cluster-kube-apiserver-operator/pull/552
/assign @stlaz

Bug 1772756: Inject kube-controller-manager pods trust stores with trusted ca bundle

---

go.mod
go.sum
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
vendor/modules.txt

* openshift/library-go@6c7d7cc3: staticpod: improve node not ready degraded message to include reason and message
* openshift/library-go@0b9c208d: build-machinery: Add human readable messages to go mod verify-deps

bump(*): vendor update

---

bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
bindata/v4.1.0/kube-controller-manager/localhost-recovery-client-crb.yaml
bindata/v4.1.0/kube-controller-manager/localhost-recovery-sa.yaml
bindata/v4.1.0/kube-controller-manager/localhost-recovery-token.yaml
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

Cert syncer syncs essential certificates to disk that are required for control plane to start. For auto cert recovery we need to wire it to use apiserver's localhost-recovery SNI endpoint with long lived certs and use long lived SA client token.
Based on https://github.com/openshift/cluster-kube-apiserver-operator/pull/663
/cc @deads2k @sttts @soltysh @mfojtik

Wire certsyncer for localhost recovery

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

We don't need revision suffix as the pod already has revision in label. The original intent was to make it clear which revision we have in artifact logs, but having this suffix makes it harder to debug or to get logs when debugging broken clusters.
Combined with kubernetes/kubernetes#87809 I think we will get into desirable state :-)
/cc @deads2k
/cc @smarterclayton

Bug 1798048: bindata: remove revision suffix from containers

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
vendor/modules.txt

Update to fix the operator. This cannot be done in the static pod code itself because some consumers like etcd still rely on those directly set conditions and removing them would break it.

bug 1798725: static pod operator cannot be composed

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/OWNERS
vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
vendor/modules.txt

ART builder are still on 1.13.4
picks up https://github.com/openshift/build-machinery-go/pull/7
/cc @mfojtik @soltysh

Bug 1801156: Enforce golang only at 1.13.4 level

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
bindata/v4.1.0/kube-controller-manager/trusted-ca-cm.yaml
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

Backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/325 on to 4.2 release. The pick wasn't clean b/c the bot failed, but it was rather minor problem so I'd consider that semi-clean :wink: 
/assign @stlaz

Bug 1802297: Inject kube-controller-manager pods trust stores with trusted ca bundle

---

pkg/operator/starter.go

csr-signer is wired for both live-reload and revisioned, but revisioned refs aren't used. Live reloading went in https://github.com/openshift/origin/pull/24577 . If we live reload we don't want to trigger revision rollout.
/cc @p0lyn0mial @soltysh @deads2k

Bug 1804239: Make csr-signer live-reloaded

---

bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml
bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrolebinding.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

Takes the roles from the openshift-apiserver repo and moves them here, these are required for the controller to function so this repository feels like the correct spot where the clusterrole and its binding should reside.
/cc @sallyom @soltysh @sttts

Add clusterrole for namespace security allocatoion controller

---

bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
pkg/operator/starter.go
pkg/operator/v411_00_assets/bindata.go

Client certs needs to be updated by cert-syncer and live reloaded for recovery to work.
/hold
Requires:

Bug 1810008: Reload client certs

---

bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
pkg/operator/starter.go
pkg/operator/v411_00_assets/bindata.go

backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/361
/hold
Requires:

[release-4.4] Bug 1771410: Reload client certs

---

Dockerfile.rhel7

backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/369
/cc @soltysh @bparees

[release-4.4] Bug 1810182: Remove wildcard COPY form Dockerfile

---

pkg/cmd/recoverycontroller/cmd.go

Fixes
```
E0316 14:12:33.320759       1 configmap_cafile_content.go:246] key failed with : missing content for CA bundle "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
E0316 14:13:24.063412       1 configmap_cafile_content.go:246] kube-system/extension-apiserver-authentication failed with : missing content for CA bundle "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
```
/cc @sttts @deads2k @soltysh

Bug 1813937: Disable serving for cert regeneration controller to avoid wrong dependency

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

The kcm uses approximately 5% of master CPU in a reasonable medium
sized workload. The kcm can be bursty in certain scenarios.
Given a 1 core per master baseline (since CPU is compressible and
shared), assign the kcm roughly 10% of that core on each master
(1/3 of the kube-apiserver usage).

Bug 1812583: Normalize CPU requests on masters

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

When `localhost-recovery-client-token` secret got created there is a race between kube-controller-manager to inject a token into it and revision controller that snapshots it. If it snapshots it before the token is injected we deploy without a token. 
Requires https://github.com/openshift/library-go/pull/764
/cc @deads2k @soltysh @sttts

Bug 1819256: Fix race for localhost-recovery-client-token snapshotting

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go

1. CSR signer changes
2. ApplySecret with the new signer Secret, missing Type
3. kube validation discards the Type and saves it with the old type
4. Update return nil, considered updated (although nothing check is the updated equals desired)
5. On next sync desired != actual, go to `#2`

Bug 1821689: Fix csr-signer update hotloop

---

pkg/cmd/recoverycontroller/cmd.go
pkg/cmd/recoverycontroller/csrcontroller.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go

When recovering from expired certificates, the refreshed `csr-controller-ca` configmap needs to be propagated to openshift-config-managed namespace to be consumed by CKAO to trust the new client certs.

Bug 1821680: Sync csr-controller-ca to openshift-config-managed namespace

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/modules.txt

backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/383
/cc @soltysh

[release-4.4] Bug 1813512: Fix race for localhost-recovery-client-token snapshotting

---

go.mod
go.sum
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/modules.txt

The Secret has the structure already, just fixing the type as per https://github.com/openshift/cluster-kube-controller-manager-operator/pull/390#issuecomment-610443497
Requires fixed `ApplySecret` from https://github.com/openshift/library-go/pull/768
/cc @deads2k

Fix CSR signer Secret type

---

pkg/cmd/recoverycontroller/csrcontroller.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go

We need new client keys to be able to start KCM before operators start to fix the mess.
On recovery flow, KASO regenerate certificates routine create new KCM client certs in openshift-config-managed namespace. We need to sync them to openshift-kube-controller-manager namespace so cert syncer can sync them to disk to be live-reloaded.

Bug 1825983: Sync new client cert-key on recovery

---

bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go
test/e2e/satokensigner_test.go
test/library/cluster_operator.go

Bug 1820687: allow patch for updating namespace

---

manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml

since openshift/cluster-version-operator#318 merged we can have our relatedObjects created immediately so must-gather always works.
/cherrypick release-4.4

Bug 1828830: add relatedobjects for immediate creation by CVO

---

pkg/cmd/resourcegraph/resourcegraph.go

[This commit](https://github.com/openshift/cluster-kube-controller-manager-operator/commit/55e685148796dca181afe4330cecc60ea598d954) updated the targetconfig controller to use the "default-ingress-cert" configmap. However, the resource graph still uses the former "router-ca" configmap. This PR updates the resource graph to use "default-ingress-cert".
__Note:__ "default-ingress-cert" ConfigMap contains the self-signed CA cert and the router's server cert.
/cc @Miciah

Bug 1830364: Updates Resource Graph to use default-ingress-cert CM

---

manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
test/e2e/operator_test.go

There is no need to use the 'on' keyword to compare
kube_poddisruptionbudget_status_expected_pods and
kube_poddisruptionbudget_status_desired_healthy because both series have
the same label set. In addition when there are 2 instances of
kube-state-metrics running, it triggers evaluation errors in Prometheus.
To ensure that the expression returns one item per (namespace,
poddisruptionbudget) tuple, it is wrapped by the 'max' aggregation
operator.

Bug 1806640: fix potential errors in Prometheus alerts

---

bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml
bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml
pkg/operator/starter.go
pkg/operator/v411_00_assets/bindata.go

Starting in Kubernetes 1.18, the GCE cloud provider implementation [requires permission](https://github.com/kubernetes/kubernetes/commit/1de2327afc9236354d815b25fc7c57b9f2b28750) to patch and update services/status.
* `bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml`:
* `bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml`: New assets.  Allow the `cloud-provider` service account to update the status of services.
* `pkg/operator/starter.go`: Add the new assets to the static resource controller if the platform is GCP.
* `pkg/operator/v411_00_assets/bindata.go`: Regenerate.

Bug 1821671: Let cloud-provider update services/status on GCP

---

pkg/operator/certrotationcontroller/satokensigner_controller.go
pkg/operator/certrotationcontroller/satokensigner_controller_test.go

I found out that `kube-controller-manager` is crashlooping when `service-account.key` is replaced with some base64 encoded fake value using this command in `openshift-kube-controller-manager-operator` namespace
`oc edit secret next-service-account-private-key`
After sometime I observed that kube-controller-manager pods are crashlooping with this error
F0130 20:49:14.680959       1 controllermanager.go:247] error starting controllers: error reading key for service account token controller: error reading private key file /etc/kubernetes/static-pod-resources/secrets/service-account-private-key/service-account.key: data does not contain a valid RSA or ECDSA private key
Thanks to @marun. He actually found this when he was explaining `saTokenSignerController` code to me.

renew next sa signing keys if they are tampered

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

just in case graceful termination made new connection logic more stringent.

wait for localhost kas to respond

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

Container can be restarted while the pods stays. For that reason, we need to check the port availability in the same process as we listen, not in an init container which isn't re-run.
Adding startup probe to avoid liveness probe timeout and killing the process.
/cc @soltysh @sttts

Fix port check

---

Makefile

`TestSATokenSignerControllerSyncCerts` is seen timing out after 10 minutes in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/405/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator/1277627343967358976/artifacts/junit_operator.xml
Let's see if it's just slower infra or the test is flaky.

Bug 1835992: Raise operator e2e test timeout

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v4.1.0/config/defaultconfig.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

If no recycler pod template is specified, the controller manager will use a default one. However, we can't rely on that one because:
1) The pod is started in the `default` namespace
2) It uses the `busybox` image
Note: the `Recycle` reclaim policy was deprecated long ago in favour of dynamic provisioning [1], but if a user happens to use this feature, we'll hit the points above.
CC @openshift/storage 
[1] https://docs.openshift.com/container-platform/4.4/storage/understanding-persistent-storage.html#reclaiming_understanding-persistent-storage

Bug: 1805908: Don't use upstream recycler pod

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/masterurl/observe_masterurl.go
pkg/operator/configobservation/masterurl/observe_masterurl_test.go

This makes us vulnerable to internal LB config that we do not own, but kubelets already break
Doing it like this leverages our existing config observation instead of creating a dynamic kubeconfig handling.
/assign @soltysh @sanchezl @tnozicka

use internal LB to avoid outages during kube-apiserver rollout

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v4.1.0/config/defaultconfig.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

This reverts commit 772810dce5557ea9521cc273d2d6c132a1d3d5a5 to prevent a CrashLoopBackOff if the recycler template isn't found (which can happen if this operator is upgraded before MCO).

Bug 1868615: Revert "Don't use upstream recycler pod"

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

This ensures that the kcm and kas can rollout independently and successfully.

Bug 1874532: using load balancer, there is no reason to wait on localhost

---

bindata/v4.1.0/kube-controller-manager/kubeconfig-cm.yaml
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

/cc @soltysh @deads2k 
Backport of #441 (since #431 was reverted)

Bug 1881534: Use internal load balancer instead of localhost 4.5

---

bindata/bootkube/manifests/00_namespace-security-allocation-controller-clusterrole.yaml

the rendered peer to https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml#L11

Bug 1886022: add new apigroup to rendered clusterrole copy

---

Dockerfile.rhel7

Updating ose-cluster-kube-controller-manager-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-kube-controller-manager-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-cluster-kube-controller-manager-operator builder & base images to be consistent with ART

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

Based on https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy we should always set `dnsPolicy: ClusterFirstWithHostNet` when we have `hostNetwork: true`. 
/assign @tnozicka

Bug 1889308: Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

This reverts commit 102d1e7026d046d1d9fe5a36c46dadbd1b5d5801 (#469) which is causing that our static pods have in-cluster dns server injected (see https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/network/dns/dns.go#L348-L352), which is problematic during upgrades. I'm talking with the node team how and if this is going to be solved in kubelet. 
/assign @tnozicka

Revert "Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork"

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
vendor/github.com/openshift/library-go/pkg/network/dialer.go
vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

this operator uses `ControlexContext` that gets the `rest.Config` for communication with Kube API from `GetKubeConfigOrInClusterConfig` which in turn sets `TCP_USER_TIMEOUT` socket option.
please check https://github.com/openshift/library-go/pull/926 to find out why we want to set this option

picks up setting `TCP_USER_TIMEOUT` socket option

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v4.1.0/config/defaultconfig.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
manifests/image-references
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v411_00_assets/bindata.go

* Reverts https://github.com/openshift/cluster-kube-controller-manager-operator/commit/a45783fc03f3bdd5e0192db53ef061ba5b00ed22. This relied on a template file created by MCO, which updates after KCMO
* Creates a ConfigMap with the recycler template in it
* Projects the ConfigMap as a file to be used by the KCM pod
* Passes the projected template file to KCM as an extended arg

Bug 1912888: Add recycler pod template as a ConfigMap

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

Communication with the AWS API in the C2S Secret region requires a custom CA bundle. This bundle is stored in the "ca-bundle.pem" entry in the cloud-config. The AWS_CA_BUNDLE environment variable informs the AWS SDK to use a custom CA bundle and to specify the location of the bundle.

Bug 1915500: support custom CA bundle for AWS C2S

---

manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
manifests/0000_25_kube-controller-manager-operator_01_operator.cr.yaml
manifests/0000_25_kube-controller-manager-operator_02_service.yaml
manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml
manifests/0000_25_kube-controller-manager-operator_04_clusterrolebinding.yaml
manifests/0000_25_kube-controller-manager-operator_05_serviceaccount.yaml
manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
manifests/0000_90_kube-controller-manager-operator_01_prometheusrole.yaml
manifests/0000_90_kube-controller-manager-operator_02_prometheusrolebinding.yaml
manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-kube-controller-manager-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

bindata/v4.1.0/kube-controller-manager/pod.yaml
pkg/operator/v411_00_assets/bindata.go

The actual use of the KCM in large production environments is
slightly lower than the request, and is fairly constant. In order
to ensure more headroom is available on small node sizes, tweak
downwards closer to the observed 40m real usage while still leaving
some headroom.
/hold
For testing with the other related changes

Bug 1920159: Adjust CPU request for controller manager more precisely

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/interfaces.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
vendor/modules.txt

By allowing to set the ciphers, KCM does not have to use the default ciphers some of which may contain security vulnerabilities.
Blocked by https://github.com/openshift/cluster-policy-controller/pull/56

bug 1844989: Allow to set --tls-cipher-suites and --tls-min-version of KCM instances through observed config

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/config/client/transport.go
vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
vendor/modules.txt

* openshift/library-go@5df90a2a: provides CancelRequest method for the PreferredHost round tripper  to facilitate cancellation
* openshift/library-go@f2434558: changes to lib-go for operator use
* openshift/library-go@9c9b6ed0: Allow StaticResourceController to ignore NotFound
* openshift/library-go@e2421125: Add ServiceMonitor sync to CSI operators
* openshift/library-go@04e8cf0b: Add ServiceMonitor to ApplyDirectly
* openshift/library-go@5cf97eb2: Return errors from ApplyDirectly
* openshift/library-go@73c4ea10: static-pods: allow fast-forward to next revision with pending installer
* openshift/library-go@d6342ca9: static-pods: avoid noise from 'for <duration>' messages
* openshift/library-go@2b890d20: convenience functions for processing unstructured arguments
* …

Bug 1949418: bump(*): vendor update

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml
bindata/bootkube/manifests/00_openshift-kube-controller-manager-operator-ns.yaml
bindata/v4.1.0/kube-controller-manager/ns.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml
manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
pkg/operator/v411_00_assets/bindata.go

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
bindata/v4.1.0/kube-controller-manager/pod.yaml
bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml
pkg/operator/v411_00_assets/bindata.go

As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please

Rename workload annotations

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

* openshift/library-go@dcdd10a4: add revision reason to status configmaps
* openshift/library-go@c805bbab: add resourceApply for prometheus rule
* openshift/library-go@eadaff0f: stop doing live gets for optional cert syncer files that don't exist on disk yet
* openshift/library-go@c96f1555: resourcesync: don't report modified on both missing target and source
* openshift/library-go@de4d21eb: update CRD apply to understand some fields are defaulted
* openshift/library-go@ed6496bd: provides a precondition checker determines if encryption controllers should synchronise
* openshift/library-go@9daa8a30: add unit tests for the preconditions checker
* openshift/library-go@69691508: wire the preconditions checker to the encryption controllers
* openshift/library-go@cb236f20: …

Bug 1961173: bump(*): vendor update

---

manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml

As of now, we are using `kube_poddisruptionbudget_status_expected_pods`
metric to decide if the PDB is its limit or it exceeded where as
`kube_poddisruptionbudget_status_current_healthy` metric
gives the exact number of healthy replicas for a
deployment or other workload that can scale. So,
changing the alerts to use correct metric so that we
don't get unnecessary signals.
cc @soltysh @smarterclayton

Bug 1954790: Use appropriate metric for PDB alerts

---

manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml

Increase the timeout for PodDisruptionBudgetAtLimit
alert as this warning level and as per the conventions
mentioned at:
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#warning-alerts
In future, we can have separate alerts for OCP specific components
and user workload specific components.

Bug 1954790: pdb: Increase PDBAtLimit timeout

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/file_utils.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
vendor/modules.txt

As of today, the dynamic certificates i.e. `kube-apiserver-certs` are accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730
This PR writes all certificates in an atomic way by first creating a temporary file, writing the content to it, and then renaming it to the original file. 
`os.Rename` calls `syscall.Rename` which in turn uses the rename syscall (Linux) which provides atomicity (https://man7.org/linux/man-pages/man2/rename.2.html)
The previous attempt didn't work as it would break the DR scripts - https://github.com/openshift/library-go/pull/1098

Bug 1963730: kube-apiserver failed to load SNI cert and key

---

bindata/v4.1.0/kube-controller-manager/recycler-cm.yaml
pkg/operator/v411_00_assets/bindata.go

See the bug for details:
https://bugzilla.redhat.com/show_bug.cgi?id=1965562
`openshift-user-critical` seems ok to me, and the request sizes are the same as what we use on some of the CSI sidecars:
https://github.com/openshift/aws-ebs-csi-driver-operator/blob/master/assets/controller.yaml#L284-L287
This container is _very_ ephemeral (as in, typically can't catch it running without adding a sleep). It just removes files from an NFS volume after it's deleted, when `persistentVolumeReclaimPolicy: Recycle` is set on the PV.
@openshift/storage @wking : any other thoughts or feedback on the requests or priority class?

Bug 1965562: recycler-for-nfs-... does not set requests or priorityClassName

---

pkg/operator/certrotationcontroller/satokensigner_controller.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

So graceful shutdown work properly and context is wired properly.

Refactor remaining controllers to factory

---

bindata/assets/kube-controller-manager/csr_approver_clusterrole.yaml

The current clusterroles don't allow the CSR approver to change the approval status of a CSR or approve the CSR requested to be signed by the `kubernetes.io/kube-apiserver-client`. The approver needs to be able to do those things, though.
/assignm @slaskawi

fix clusterroles for the CSR approver

---

bindata/assets/kube-controller-manager/pod.yaml
bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml

this is required for cluster-policy-controller refactoring: https://github.com/openshift/cluster-policy-controller/pull/65
- pass pod metadata and kubeconfig to the controller
- add new role for getting pods (required by event recorder)

update cluster-policy-controller configuration

---

bindata/assets/config/default-cluster-policy-controller-config.yaml
bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml

remove configuration that was made obsolete by recent cluster-policy-controller updates https://github.com/openshift/cluster-kube-controller-manager-operator/pull/545 and https://github.com/openshift/cluster-policy-controller/pull/65

remove unused cluster-policy-controller configuration

---

pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go

Merging #525 appears to have broken the KCMO when it comes to setting this new flag
```
Operator degraded (TargetConfigController_SynchronizationError): TargetConfigControllerDegraded: "configmap": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field KubeControllerManagerConfig.extendedArguments of type v1.Arguments
```
Based on the other extended arguments observers, I've updated the observer here. Testing on a real cluster now, will report back shortly.

Cloud Volume Observer: Extended arguments must be a slice

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go

When KCM starts with a feature gate that it doesn't know, it logs an error. This PR should prevent that from happening by excluding the openshift only `ExternalCloudProvider` feature gate from the list of feature gates passed to KCM.
This relies on the functionality implemented in library-go to exclude blacklisted feature gates, as per https://github.com/openshift/library-go/blob/master/pkg/operator/configobserver/featuregates/observe_featuregates.go#L26

Bug 1989073: Exclude openshift only CloudProvider feature gate from KCM config

---

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml

The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.

Bug 1986829: metrics: use client cert auth for metrics scraping

---

bindata/assets/kube-controller-manager/ns.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-kube-controller-manager` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @deads2k @sttts

podsecurity: enforce privileged for openshift-kube-controller-manager namespace

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go

When external cloud provider is applied, the operator should set the condition that it doesn't own this component anymore.
It will help migrating the system from in-tree to external cloud providers:
https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/out-of-tree-provider-support.md#migration-procedure

Set operator condition that it doesn't own cloud provider

---

bindata/assets/kube-controller-manager/svc-cluster-policy-controller.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
pkg/operator/starter.go

updates the ServiceMonitor so it also collects metrics from cluster-policy-controller. 
This will start working after the correct ports get opened on the nodes - see installer PR
TODO:

collect metrics for cluster-policy-controller

---

bindata/assets/kube-controller-manager/svc.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml

https://github.com/openshift/cluster-kube-controller-manager-operator/pull/554 changes need to be added incrementally since it was failing during upgrades (https://github.com/openshift/cluster-kube-controller-manager-operator/pull/574#issuecomment-974535812).
We need to backport this to 4.9 and then pin this version in build-suggestions (https://github.com/openshift/cincinnati-graph-data/pull/1220)

update KCM metrics service selector

---

manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml
pkg/operator/starter.go

Add kube-system namespace to relatedobjects
We noticed that the operator is using a configmap for leader election that is not a related resource and thus is not gathered by must-gather. Adding the namespace as a related resource will correct this.

Collect kube-system namespace as a related resource to kube-controller-manager operator

---

cmd/cluster-kube-controller-manager-operator/main.go
go.mod
go.sum
pkg/cmd/recoverycontroller/cmd.go
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
vendor/modules.txt

```
2021-11-03T04:25:43.102203390Z F1103 04:25:43.102194       1 cmd.go:48] lstat /etc/kubernetes/static-pod-resources/kube-scheduler-certs: no such file or directory
2021-11-03T04:25:43.194947275Z goroutine 1 [running]:
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.stacks(0xc000012001, 0xc0001c81c0, 0x84, 0xda)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:1026 +0xb9
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).output(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0xc0003c81c0, 0x1, 0x2f628ac, 0x6, 0x30, 0x414600)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:975 +0x1e5
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).printDepth(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000496910, 0x1, 0x1)
2021-11-03T04:25:43.194947275Z …
```

bug 2026352: Sync with the latest openshift/library-go@master to pick pruner cert dir check

---

bindata/assets/kube-controller-manager/svc.yaml
manifests/0000_25_kube-controller-manager-operator_02_service.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

- default self-signed certificate is used when service-ca controller is
lagging or unable to start
- kcm pod will be redeployed and the certificate changed as soon as serving-cert is created by
service-ca

Bug 2045872: allow cluster-policy-controller to fallback to default cert

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

picking up openshift/library-go#1302
pick of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/597 in 4.10

bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes

---

bindata/bootkube/manifests/00_podsecurity-admission-label-syncer-controller-clusterrole.yaml
bindata/bootkube/manifests/00_podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
pkg/cmd/render/render_test.go

Adds clusterrole and its binding for https://github.com/openshift/cluster-policy-controller/pull/75
/hold
until the related PR gets approved

add RBAC for PSa label syncing controller

---

bindata/bootkube/manifests/0000_00_namespace-openshift-infra.yaml

Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
During an e2e run for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1339 (https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1339/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws/1526469279988322304): ` [sig-storage] PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted. [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less`:
```
➜  ~ kubectl -n …
```

Bug 2086519: bindata/../namespace-openshift-infra: label namespace as privileged

---

manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
test/e2e/operator_test.go

meaning alert should not fire when currentHealthy == 0 and desiredHealthy == 0
It makes sense to not fire an alert if there is no application to disrupt

Bug 2053622: PodDisruptionBudgetAtLimit should not alert when no app/pods exist

---

bindata/assets/kube-controller-manager/podsecurity-admission-label-syncer-controller-clusterrole.yaml
bindata/assets/kube-controller-manager/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
pkg/operator/starter.go

These were missing in upgraded clusters.
/assign @soltysh

Bug 2097186: add rbac roles for the podsecuritylabelsyncer even outside bootkube

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/images.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/modules.txt

This PR bumps the openshift library go dependency to include https://github.com/openshift/library-go/pull/1383.
This will mean that OpenStack is always set to external and will force the migration from in-tree to out-of-tree for OpenStack.
This needs to be merged simultaneously with https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/199
I used cluster bot to test this with the respective CCCMO and KCMO PRs, with two results:
* [First attempt - failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-openstack/1551878461327413248)
* [Second attempt - passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-openstack/1551942225204613120)
This test vendored the …

Update library-go to set OpenStack provider to external

---

go.mod
go.sum
vendor/modules.txt

Following on from #641, we force merged dependencies from a branch. This resets back to the updated library-go commit and removes the replace statement.
No diff to the vendor.

Reset Go mod after openstack library-go bump

---

bindata/assets/kube-controller-manager/namespace-openshift-infra.yaml
bindata/bootkube/manifests/0000_00_namespace-openshift-infra.yaml

`baseline` is not enough for the recycler pod.
Without this PR:
```
Events:
Type     Reason               Age   From                         Message
----     ------               ----  ----                         -------
Warning  VolumeFailedRecycle  23s   persistentvolume-controller  Recycle failed: unexpected error creating recycler pod:  pods "recycler-for-pv0001" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volume "vol")
```
With this PR:
```
Events:
Type    Reason          Age   From                         Message
----    ------          ----  ----                         -------
Normal  RecyclerPod     11m   persistentvolume-controller  Recycler pod: Successfully assigned openshift-infra/recycler-for-pv0001 to ci-ln-clddrdk-72292-dftbl-worker-a-t47t2 by …
```

Bug 2101843: Label openshift-infra namespace as privileged

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/github.com/openshift/library-go/pkg/config/serving/server.go
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

[Trt-589](https://issues.redhat.com//browse/Trt-589) is researching an issue where installer pods timeout, shutdown and enter a failed state triggering KubePodNotReady alerts.  library-go was updated to add milestone logging to track the progress and track down the issue.  Bumping the version to pull those changes in.

trt-589 bump library-go

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml

To address:
```
Oct 11 21:22:11 cnfde10.ptp.lab.eng.bos.redhat.com bash[13032]: E1011 21:22:11.692287   13032 file.go:236] "Static Pod is managed but errored" err="managed container kube-controller-manager does not have Resource.Requests" name="bootstrap-kube-controller-manager-cnfde10.ptp.lab.eng.bos.redhat.com" namespace="kube-system"
```
Copy-pasting the requests from https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/bindata/assets/kube-controller-manager/pod.yaml

bootstrap-kube-controller-manager: specify resources.requests

---

pkg/operator/starter.go

- was used for making a switch from configMaps to leases in leader election
we noticed this in https://coreos.slack.com/archives/CC3CZCQHM/p1667571136730989
Also you can see the TODOs in the removed files (that are still present for the controller to work).
- https://github.com/openshift/cluster-kube-controller-manager-operator/blob/08d7aed96479b280a23c1e7c2075c98164fc95bd/bindata/assets/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml#L5
- https://github.com/openshift/cluster-kube-controller-manager-operator/blob/08d7aed96479b280a23c1e7c2075c98164fc95bd/bindata/assets/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml#L5

OCPBUGS-3283: remove unnecessary RBAC

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
pkg/cmd/render/render_test.go

These flags were removed in https://github.com/kubernetes/kubernetes/pull/112120, based on [the defaults](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md#logging-defaults)  we should be good with just dropping these flags.

Drop flags removed in k8s 1.26

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/modules.txt

This PR updates the library-go dependency to include [a bump to move the vSphere cloud provider to out-of-tree](https://github.com/openshift/library-go/pull/1451). Note this PR must be merged at the same time as a [PR to CCMO](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/214) making the same bump to avoid a build that contains only one of the two bumps.
Tested with [cluster bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-vsphere-modern/1612407690103885824)

[OCPCLOUD-1818] Update library-go dependency to move vSphere to out of tree

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/modules.txt

Post #687, need to fix the library-go vendor to point it back to the main branch now the upstream change has merged

Fixup vendor after library-go update

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

Backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/693

OCPBUGS-7369: Guard pod set readiness probe endpoint explicitly

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

Backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/699

OCPBUGS-7756: Guard pod set readiness probe endpoint explicitly

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/crypto/keys.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/state/types.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/modules.txt

This PR updates the library-go dependency to include [a bump to move the AWS cloud provider to out-of-tree](https://github.com/openshift/library-go/pull/1485). Note this PR must be merged at the same time as a [PR to CCMO](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/232) making the same bump to avoid a build that contains only one of the two bumps.
Tested with [Cluster Bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1633075931457261568)

[OCPCLOUD-1988] Update library-go dependency to move AWS to out of tree

---

bindata/assets/config/defaultconfig.yaml
pkg/cmd/render/render_test.go

Manually picked of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/715
/assign @tkashem

OCPBUGS-7785: migrate to using lease objects for leader election

---

pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go

We believe that in 4.14, the external-cloud-volume-plugin is no longer required for AWS. CSI migration went GA in 4.12 so by 4.14 all volumes should have been migrated across and the in-tree mechanism should no longer be required
CC @bertinatto @soltysh @jsafrane

OCPBUGS-11352: AWS should not use external-cloud-volume-plugin post CSI migration

---

cmd/cluster-kube-controller-manager-operator/main.go
pkg/cmd/render/render.go
pkg/cmd/render/render_test.go
pkg/cmd/render/testdata/rendered/custom-fg/featuregate-custom.yaml
pkg/cmd/render/testdata/rendered/default-fg/featuregate.yaml
pkg/cmd/render/testdata/rendered/duplicate-fg/featuregate-copy.yaml
pkg/cmd/render/testdata/rendered/duplicate-fg/featuregate.yaml
pkg/cmd/render/testdata/rendered/mismatched-fg/featuregate-custom.yaml
pkg/cmd/render/testdata/rendered/mismatched-fg/featuregate.yaml
pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go
pkg/operator/starter.go

This updates the cloud provider and external volume plugin config observers to use the new feature gates accessor interface. This will allow the feature gate status observation to be determined by the cluster config operator in a synchronised way across the multiple interested operators.
Required to get Azure and GCP CCMs to be promotable in a single PR.
/hold until library-go PR is merged
CC @deads2k

[OCPCLOUD-2034] Update cloud provider tests with feature gate changes

---

pkg/operator/configobservation/cloud/observe_cloud_volume_plugin.go
pkg/operator/configobservation/cloud/observe_cloud_volume_plugin_test.go

updated azure unit tests for 4.13 to reflect tech preview status.

 [release-4.13] OCPBUGS-11353: AWS should not use external-cloud-volume-plugin post CSI migration

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml

Previously deprecated klog flags will be removed completely in kube 1.26. Logs of bootstrap pods were previously using the --log-file flag, will be available in the cri-o container logs instead.
Blocks https://github.com/openshift/cluster-policy-controller/pull/113.

OCPBUGS-13579: Drop flags removed in k8s 1.26

---

bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml
bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-rolebinding.yaml
pkg/operator/starter.go

after a recent kube & library-go update https://github.com/openshift/cluster-policy-controller/pull/113 we no longer need RBAC for configmaps in cluster-policy-controller as we have switched to leases exclusively

OCPBUGS-13579: remove RBAC for cluster-policy-controller CM leader election

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

This PR bumps library-go to fetch the changes come with;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

[release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

---

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml

We forgot to bump kube deps to 1.26 in 4.13. We are required to bump them to fix a https://github.com/openshift/cluster-policy-controller/pull/135 CVE. These changes are required to start a cpc container in the boostrap phase:
```
Previously deprecated klog flags will be removed completely in kube 1.26.
Logs of bootstrap pods were previously using the --log-file flag, will be available in the cri-o container logs instead.
```

OCPBUGS-21103: Drop flags removed in k8s 1.26 [4.13]

---

go.mod
go.sum
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/modules.txt

- revision_controller: be more verbose about LatestAvailableRevision and resourceVersion
- add pdbUnhealthyPodEvictionPolicy option to a GuardController
- guard: add workload partitioning annotation

OCPBUGS-23462: bump(library-go)

---

manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml

Remove "include.release.openshift.io/ibm-cloud-managed:" annotation to CVO not to deploy the service monitor

 OCPBUGS-18115: Remove "include.release.openshift.io/ibm-cloud-managed:" annotation 

---

pkg/operator/starter.go

This change removes the cloud-provider ClusterRole, ClusterRoleBinding and ServiceAccount that are no longer required from 4.16

OCPBUGS-5825: Removes legacy cloud-provider resources

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/modules.txt

Pulling https://github.com/openshift/library-go/pull/1602

OCPBUGS-27063: bump(library-go)=release-4.14

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/modules.txt

Pulling https://github.com/openshift/library-go/pull/1602

OCPBUGS-27066: bump(library-go)=release-4.13

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/modules.txt

Pulling https://github.com/openshift/library-go/pull/1602

OCPBUGS-27068: bump(library-go)=release-4.12

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go

This change replaces the current logic to set the CloudControllerOwner condition to instead remove the condition whenever it is seen on the ClusterOperator. This is being done because all cloud controllers are now external and cannot be owned by the KCMO.

OCPCLOUD-2515: remove CloudControllerOwner condition

---

go.mod
go.sum
pkg/operator/certrotationcontroller/certrotationcontroller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/modules.txt

UseSecretUpdateOnly is intended as a short term hack for a very specific use case,
and it works in tandem with a particular carry patch applied to the openshift kube-apiserver.
(https://github.com/openshift/kubernetes/pull/1924)
we will remove this when we migrate all of the affected secret
objects to their intended type: https://issues.redhat.com/browse/API-1800
in short tls secrets used by this operator are reconciled
by multiple controllers ([the cert controller run by the operator](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/operator/certrotationcontroller/certrotationcontroller.go#L85) and [the same controller run by the recovery pod](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/cmd/recoverycontroller/c …

OCPBUGS-31807: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode

---

bindata/bootkube/manifests/secret-csr-signer-signer.yaml

SecretTypeTLS is a deprecated type, which gets converted to kubernetes.io/tls when controller parses. Changing this type to supported to make controller skip convertion on initial install.

API-1800: bindata: convert SecretTypeTLS secrets

---

Dockerfile.rhel7
go.mod

OCPBUGS-34281: Updating ose-cluster-kube-controller-manager-operator-container image to be consistent with ART for 4.17

---

bindata/bootkube/manifests/secret-csr-signer-signer.yaml

Ensure that the secret has necessary annotations applied on creation time, so that the controller didn't have to wait for changes in the secret to apply ownership annotations. This fixes a regression after https://github.com/openshift/cluster-kube-controller-manager-operator/pull/804

OCPBUGS-34859: manifests: set owning-component for csr-signer-signer

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/modules.txt

This is motivated by the installer controller fix in library-go. 
cc @benluddy

OCPBUGS-48701: Bump to latest library-go

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

- and the kube-scheduler-operator has already set the TraceAll to 10, as seen in https://github.com/openshift/cluster-kube-scheduler-operator/blame/b1cc4471e2f6c5dc81b2b9471f4634f1ecdb88b4/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L267
- and the microshift has also bump this TraceAll loglevel to 10  https://github.com/openshift/microshift/pull/4400
If we use TraceALL, we want to trace all the logs really, and some important k8s logs are v(10)

NO-ISSUE: Bump TraceAll log level to v=10

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Ensure CA description is set to match CKAO managed configmap: https://github.com/openshift/cluster-kube-apiserver-operator/blob/main/bindata/bootkube/manifests/configmap-csr-controller-ca.yaml#L9C34-L9C123

NO-JIRA: targetconfigcontroller: set description for csr-controller-ca

---

bindata/assets/kube-controller-manager/pod.yaml
bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml

There are controllers that attempt to create /etc/kubernetes/kubelet-plugins which fail because of the readonly filesystem. This means that the KCM container cannot be readonly.
Not doing a revert as there are other containers in the KCM pod that could be read only root filesystem

RFE-4154: Remove readOnlyRootFilesystem from KCM container

---

go.mod
go.sum
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/version.go
vendor/modules.txt

Instead of re-creating configmap from scratch every time this function should attempt to use existing configmap and replace the contents only. This would prevent extra configmap updates when metadata changes.
See similar PR in CKAO: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1812

OCPBUGS-60473: Optimistically update Kube Server and Client CA bundles

---

.gitignore
cmd/cluster-kube-controller-manager-operator-tests-ext/main.go
go.mod
test/extended/README.md
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/logging.go
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/parallel.go
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/util.go
vendor/modules.txt

- Add JUnit reporter configuration to generate XML reports for CI integration
- Create comprehensive README.md for OTE implementation based on openshift-apiserver example
- Add report.json and junit.xml to .gitignore to exclude generated files
- Document test execution, CI integration, and architecture details

CNTRLPLANE-1275: Add JUnit reporter configuration and README for OTE

---

pkg/operator/certrotationcontroller/certrotationcontroller.go

This prevents CA bundle from being updated by sidecar running in RefreshOnlyWhenExpired=true mode

[release-4.19] OCPBUGS-60682: certrotationcontroller: set RefreshOnlyWhenExpired for CA bundle

---

pkg/operator/resourcesynccontroller/resourcesynccontroller.go

Writes from the instance of resourcesynccontroller in the operator can contend with writes from the recovery sidecar's instance of the same controller. This is a preexisting issue, and the controller doesn't have an effective way to limit resync frequency. Adding some fixed latency to each sync in this way sets an upper bound on the churn rate when the two instances get into a feedback cycle.
The separate issues that can create a feedback cycle (e.g. the resourcesynccontroller degraded operator status condition is shared by both instances) should be separately addressed "soon".

OCPBUGS-62255: Throttle resourcesynccontroller on pairs with dual writers.

---

pkg/operator/resourcesynccontroller/resourcesynccontroller.go

Writes from the instance of resourcesynccontroller in the operator can contend with writes from the recovery sidecar's instance of the same controller. This is a preexisting issue, and the controller doesn't have an effective way to limit resync frequency. Adding some fixed latency to each sync in this way sets an upper bound on the churn rate when the two instances get into a feedback cycle.
The separate issues that can create a feedback cycle (e.g. the resourcesynccontroller degraded operator status condition is shared by both instances) should be separately addressed "soon".
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/881

[release-4.20] OCPBUGS-55217: Throttle resourcesynccontroller on pairs with dual writers.

---

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml

As documented in [1], the platform Prometheus servers are configured with a scrape class named `tls-client-certificate-auth` which automatically injects the client certificate and key files for mutual TLS into the scrape configuration of the service.
This commit also removes the `namespaceSelector` field of the service monitors: it isn't required when the service monitor and service are located in the same namespace. It also adjusts the `jobLabel` value to refer to the `app` label of the service.
[1] https://rhobs-handbook.netlify.app/products/openshiftmonitoring/collecting_metrics.md/#configuring-prometheus-to-scrape-metrics

NO-ISSUE: Use scrapeClass for service monitors
