bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Should unblock the cluster up control plane. This will eventually move to scheduler and is temporary.
=> do not use scheduler config for now

bindata/v3.11.0/kube-apiserver/deployment.yaml, manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
/assign @abhinavdahiya @mfojtik
=> tolerate any taint

pkg/test/assets_test.go
=> Add basic yaml linting test

pkg/operator/starter.go
@deads2k i think this is what you meant and we want in all operators? ;-)
(second commit)
=> Ensure operator config exists and has the right image when operator start

manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml, manifests/image-references
=> add image references

cmd/cluster-kube-controller-manager-operator/render/render.go
This was only temporary to get us going.
=> render: remove hacky scheduler support

bindata/bootkube/manifests/kube-system-configmap-kube-controller-manager-config.yaml, cmd/cluster-kube-controller-manager-operator/render/options/config.go, cmd/cluster-kube-controller-manager-operator/render/options/generic.go, cmd/cluster-kube-controller-manager-operator/render/options/manifest.go, cmd/cluster-kube-controller-manager-operator/render/render.go, pkg/test/assets_test.go
This is the first steps towards a shared render command. In a follow-up we move everything but the cobra command construction into another repo.
=> render: switch to options/config pattern

Makefile
=> Makefile: sync with apiserver

manifests/0000_12_cluster-kube-controller-manager-operator_01_config.crd.yaml, pkg/operator/starter.go
This adds reporting back to the CVO.
=> add clusteroperator status reporting

pkg/operator/observe_config.go, pkg/operator/operator.go, pkg/operator/starter.go, pkg/operator/sync_kubecontrollermanager_v311_00.go
cc @deads2k @mrogers950 
Depends on https://github.com/openshift/cluster-kube-controller-manager-operator/pull/62
=> add cabundle config observer

cmd/cluster-kube-controller-manager-operator/render/render.go
Counterpart of openshift/cluster-kube-apiserver-operator#91 and prerequisite for #63.
=> render: temporary --disable-phase-2

manifests/0000_12_cluster-kube-controller-manager-operator_06_deployment.yaml
Fix up https://github.com/openshift/cluster-kube-controller-manager-operator/pull/63/files#r229556099
@deads2k @sttts
=> fix OPERATOR_IMAGE image pull spec

bindata/v3.11.0/kube-controller-manager/pod.yaml, pkg/operator/v311_00_assets/bindata.go
=> add namespace to static pod

pkg/apis/kubecontrollermanager/v1alpha1/types.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v311_00.go
=> Remove references to apiserver.

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml, pkg/operator/starter.go, pkg/operator/v311_00_assets/bindata.go
We forgot the serviceaccount key and the cert signer key+cert in phase 3.
=> phase-3: add missing certs+keys

pkg/operator/observe_config.go, pkg/operator/observe_config_test.go, pkg/operator/starter.go
enabled config observation status
switched to using Listers
=> update operator config observation status

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml, glide.lock, pkg/operator/v311_00_assets/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
A bump plus a default QPS change
@smarterclayton this should make the e2e tests faster
@openshift/sig-master fyi
=>  fix kube-controller-manager qps

manifests/0000_12_cluster-kube-controller-manager-operator_00_namespace.yaml, manifests/0000_12_cluster-kube-controller-manager-operator_02_service.yaml, manifests/0000_90_cluster-kube-controller-manager-operator_01_prometheusrole.yaml, manifests/0000_90_cluster-kube-controller-manager-operator_02_prometheusrolebinding.yaml, manifests/0000_90_cluster-kube-controller-manager-operator_03_servicemonitor.yaml
=> add service monitor resources for operator

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
lgtm'd via https://github.com/openshift/cluster-kube-controller-manager-operator/pull/107
=> make the cloud platform detection tolerant of libvirt

manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml
wait for a few greens
/test e2e-aws
=> add clusteroperator resource to CVO payload

bindata/v3.11.0/kube-controller-manager/operator-config.yaml, bindata/v3.11.0/kube-controller-manager/pod.yaml, bindata/v3.11.0/kube-controller-manager/sa.yaml, bindata/v3.11.0/kube-controller-manager/svc.yaml, manifests/0000_12_kube-controller-manager-operator_02_service.yaml, manifests/0000_12_kube-controller-manager-operator_03_configmap.yaml, manifests/0000_12_kube-controller-manager-operator_04_clusterrolebinding.yaml, manifests/0000_12_kube-controller-manager-operator_05_serviceaccount.yaml, manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml, manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml, manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml, pkg/operator/starter.go, pkg/operator/staticpod_interface.go, pkg/operator/target_config_reconciler.go, pkg/operator/v311_00_assets/bindata.go
peer to https://github.com/openshift/cluster-kube-apiserver-operator/pull/191
=>  tighten resource names

bindata/v3.11.0/kube-controller-manager/pod.yaml, manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
@smarterclayton @deads2k @derekwaynecarr
=> set cpu request for pod and operator

manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml
=> explicitly list metrics port as first containerPort

manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml, manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
=> use the real service-ca for monitoring

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go
New doc on Infrastructure is that we need to tolerate unknown ones.
@mfojtik we need to update this code to read the real Infrastructure type.
=> tolerate unknown cloud provider

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml, pkg/operator/v311_00_assets/bindata.go
Disable local-storage feature for now.
Fixes JIRA - STOR-183
=> Disable persistent-local-volumes

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go, pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/configobservation/interfaces.go, pkg/operator/starter.go
Get cloud provider from `infrastructures.config.openshift.io/cluster` instead of cluster `cm/cluster-config-v1.kube-system`.
=> observe cloud provider from config api

glide.lock, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
https://github.com/openshift/library-go/pull/293
https://github.com/openshift/library-go/pull/292
=> bump(library-go): improve logging of what causes a static pod rollout

manifests/0000_12_kube-controller-manager-operator_03_version-mapping.yaml, manifests/0000_12_kube-controller-manager-operator_06_deployment.yaml, manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml
See: https://github.com/openshift/cluster-kube-apiserver-operator/pull/308
=> minor fitting to set versions for our operator

pkg/operator/certrotationcontroller/satokensigner_controller.go
We don't have to fail the operator on this error, it is transient. This will type the error and make the sync skip it.
=> certrotationcontroller: do not fail on unexpected addresses

bindata/v3.11.0/kube-controller-manager/defaultconfig.yaml, pkg/operator/v311_00_assets/bindata.go
Same as https://github.com/openshift/cluster-kube-apiserver-operator/pull/344 
cc @wongma7 @deads2k
=> re-enable local storage

bindata/v3.11.0/kube-controller-manager/pod.yaml, pkg/operator/v311_00_assets/bindata.go
Followup from #197 to shorten the timeout to 30s per @sttts comment.
/assign @sttts
=> Shorten wait time for the free port

bindata/v3.11.0/kube-controller-manager/pod.yaml, pkg/operator/v311_00_assets/bindata.go
=> switch port check to insecure

pkg/operator/configobservation/cloudprovider/observe_cloudprovider.go, pkg/operator/configobservation/cloudprovider/observe_cloudprovider_test.go
Add support for azure platform cloud provider parameter
=> Add support for Azure platform

Makefile, test/e2e/operator_test.go, test/library/client.go
Layout initial support for adding e2e tests.
=> Add test-e2e make target

.travis.yml
/assign @tnozicka @sttts
Requires https://github.com/openshift/release/pull/3487
=> Switch openshift/kcm-o to go1.11

glide.lock, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
saves one minute per operator in the upgrade
=> tightens leader election

glide.lock, vendor/github.com/openshift/api/config/v1/types_cluster_version.go, vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go, vendor/github.com/openshift/api/operator/v1/types_etcd.go, vendor/github.com/openshift/api/operator/v1/types_serviceca.go, vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go, vendor/github.com/openshift/api/security/v1/generated.proto, vendor/github.com/openshift/api/security/v1/types.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
=> emit events for version changes

bindata/bootkube/manifests/00_openshift-kube-controller-manager-ns.yaml, bindata/v3.11.0/kube-controller-manager/ns.yaml, manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml, pkg/operator/v311_00_assets/bindata.go
/cc @brancz @paulfantom @deads2k @sttts
=> monitor kube controller manager

Dockerfile, Dockerfile.rhel7
=> Switch to go1.12

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
wait for five minutes before using a new csr signer so that the KAS has time to catch up.
I have a prettier conditional function, but conditional apply is going to be icky.
=> only use the new CSR signer after five minute so KAS is up to date

pkg/operator/configobservation/clustername/observeinfraid.go, pkg/operator/configobservation/clustername/observeinfraid_test.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Adds cluster-name argument to extendedArguments with a value of the cluster's infra ID.
=> Add observer for the cluster's infra ID and set it as the cluster-name argument

glide.lock, vendor/github.com/evanphx/json-patch/go.mod, vendor/github.com/evanphx/json-patch/go.sum, vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go, vendor/golang.org/x/tools/go/analysis/passes/printf/testdata/src/a/a.go, vendor/golang.org/x/tools/go/analysis/passes/printf/types.go, vendor/golang.org/x/tools/internal/gopathwalk/walk.go, vendor/golang.org/x/tools/internal/lsp/cache/gofile.go
=> vendor: bump library-go for updated cloudprovider observer

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
Counter part to https://github.com/openshift/installer/pull/2275.
=> bootstrap: log to /var/log/bootstrap-control-plane/kube-controller-manager.log

OWNERS
=> Add myself as approver for kcm-o

Dockerfile, Dockerfile.rhel7, Makefile
Similar to https://github.com/openshift/cluster-kube-scheduler-operator/pull/169
/assign @tnozicka
=> Fix makefile to allow make images to work

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
https://github.com/openshift/cluster-monitoring-operator/pull/516
=> move KubeControllerManagerDown alert to this operator

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
/assign @smarterclayton @eparis @sferich888 @cuppett
=> Bug 1762888: alert when number of expected pods is equal or lower than desired healthy pods in a PDB

bindata/v4.1.0/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml, bindata/v4.1.0/kube-controller-manager/leader-election-cluster-policy-controller-rolebinding.yaml, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v411_00_assets/bindata.go
this is a pick of 425dfc3970149b6f1d28d
/cc @soltysh
=> Bug 1767047: move rbac for cluster-policy-controller leader lock to kcm-o

manifests/0000_90_kube-controller-manager-operator_05_alert-pdb.yaml
=> Add namespace to PDB limit alert

manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml, pkg/operator/starter.go
=> Bug 1735509: monitoring: move service monitor RBAC rules to manifests/

bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml, bindata/v4.1.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v411_00_assets/bindata.go, test/e2e/operator_test.go
Backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/311
=> Bug 1718061: Fix KCM leader election configmap deletion recovery

bindata/v3.11.0/kube-controller-manager/leader-election-kube-controller-manager-role-kube-system.yaml, bindata/v3.11.0/kube-controller-manager/leader-election-kube-controller-manager-rolebinding-kube-system.yaml, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v311_00_assets/bindata.go, test/e2e/operator_test.go
Backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/311
=> Bug 1781240: Fix leader election configmap deletion recovery

Makefile
=> Bug 1798868: Remove clean target that is already automatic for a while

bindata/v4.1.0/kube-controller-manager/pod.yaml, pkg/operator/v411_00_assets/bindata.go
Identical to https://github.com/openshift/cluster-kube-apiserver-operator/pull/753
=> Preselect cotnainer name for oc

pkg/operator/starter.go
backport of #351
/cc @p0lyn0mial @soltysh @deads2k
=> [release-4.4] Bug 1805791: Make csr-signer live-reloaded

test/e2e/operator_test.go
Part of https://issues.redhat.com/browse/WRKLDS-73 [Improve e2e tests for kcm-o & ks-o], just trying to add some more basic e2e test coverage
=> Add basic operator tests

Dockerfile.rhel7
It doesn't work with docker and buildah, only image builder.
/cc @soltysh @bparees
=> Bug 1810181: Remove wildcard COPY form Dockerfile

manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml
=> Bug 1770303: alert when number of expected pods is equal or lower than desired healthy pods in a PDB

pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
/assign @deads2k 
Picks https://github.com/openshift/cluster-kube-apiserver-operator/pull/729/ and https://github.com/openshift/cluster-kube-apiserver-operator/pull/726 to kcm-o
/hold 
for 4.5
=> Switch to staticresource control loop

pkg/cmd/recoverycontroller/cmd.go, pkg/cmd/recoverycontroller/csrcontroller.go, pkg/operator/certrotationcontroller/certrotationcontroller.go
We are already syncing the by products but the main cert rotation loop got left somewhere. 
=> Bug 1820610: Refresh csr-signer in recovery flow

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/390
/cc @soltysh
=> [release-4.4] Bug 1821690: Fix csr-signer update hotloop

pkg/cmd/recoverycontroller/cmd.go, pkg/cmd/recoverycontroller/csrcontroller.go, pkg/operator/certrotationcontroller/certrotationcontroller.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/385
=> [release-4.4] Bug 1820613: Refresh csr-signer in recovery flow

pkg/cmd/recoverycontroller/cmd.go, pkg/cmd/recoverycontroller/csrcontroller.go, pkg/operator/certrotationcontroller/certrotationcontroller.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/389
/hold
requires https://github.com/openshift/cluster-kube-controller-manager-operator/pull/386
/cc @soltysh
=> [release-4.4] Bug 1821683: Sync csr-controller-ca to openshift-config-managed namespace

bindata/v4.1.0/kube-controller-manager/pod.yaml, pkg/operator/v411_00_assets/bindata.go
=> [release-4.3] Bug 1822770: Normalize CPU requests on masters

pkg/cmd/recoverycontroller/csrcontroller.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/400
/cc @deads2k @soltysh @mfojtik
=> [release-4.4] Bug 1825987: Sync new client cert-key on recovery

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Previously the operand always added the serving service ca to token secrets. 
https://github.com/openshift/origin/pull/24956 will disable this behavior by default but allow it to be enabled via an env var. 
This PR supports setting the env var if an `UnsupportedConfigOverride` named `enableDeprecatedAndRemovedServiceCAKeyUntilNextRelease_ThisMakesClusterImpossibleToUpgrade` is set to true. 
When the override is set to true, the operator will be marked as not upgradeable. This is a temporary measure to allow but discourage the behavior prior to its removal in 4.6.
/cc @sttts @deads2k @soltysh
=> Bug 1813894: Enable the addition of service ca to token secrets via UnsupportedConfigOverride

bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml, bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v411_00_assets/bindata.go
backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/415
/cc @soltysh @Miciah
=> [release-4.4] Bug 1816806: Fix gce cloud provider permissions

bindata/v4.1.0/kube-controller-manager/pod.yaml, pkg/operator/v411_00_assets/bindata.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421
/cc @soltysh
=> [release-4.5] Bug 1851390: Fix port check

bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-binding.yaml, bindata/v4.1.0/kube-controller-manager/gce/cloud-provider-role.yaml, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v411_00_assets/bindata.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/415
/cc @soltysh @Miciah
=> [release-4.3] Bug 1853171: Fix gce cloud provider permissions

bindata/v4.1.0/kube-controller-manager/pod.yaml, pkg/operator/v411_00_assets/bindata.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421
/cc @soltysh
=> [release-4.4] Bug 1851397: Fix port check 4.4

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, vendor/github.com/openshift/library-go/pkg/operator/status/version.go, vendor/modules.txt
proof of openshift/library-go#865
=> bump to delay version update until operand updated

pkg/cmd/render/render.go
This part 1 one of the three part series to render the cluster-policy-controller in bootstrap pod
=> bug 1861917: add render --cluster-policy-controller-image to add that controller to  bootstrap yaml

bindata/v4.1.0/kube-controller-manager/pod.yaml, pkg/operator/v411_00_assets/bindata.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421
/cc @soltysh
=> Bug 1851398: Check port availability in the same container

go.mod, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
CPC config was in a wrong location causing cpc on botstrap to crashloop.
Ness to be followed up with https://github.com/openshift/installer/pull/4178 and then enforcing the flag
/cc @soltysh
=> Bug 1861917: Fix bootstrap cpc

manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml, pkg/operator/starter.go
A demonstration of the code we're talking about.
=> bug 1874056: add debugging for machine-api, mco, and node teams

pkg/cmd/render/render.go
Followup to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/449
Requires:
/hold
/cc @soltysh
=> Bug 1861917: Enforce cpc config

bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml, bindata/bootkube/manifests/00_namespace-security-allocation-controller-clusterrole.yaml, bindata/bootkube/manifests/00_namespace-security-allocation-controller-clusterrolebinding.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
=> Bug 1861917: Fix bootstrap cpc config file location, certs and RBAC

go.sum, manifests/0000_25_kube-controller-manager-operator_00_namespace.yaml, manifests/0000_25_kube-controller-manager-operator_01_operator.cr.yaml, manifests/0000_25_kube-controller-manager-operator_02_service.yaml, manifests/0000_25_kube-controller-manager-operator_03_configmap.yaml, manifests/0000_25_kube-controller-manager-operator_04_clusterrolebinding.yaml, manifests/0000_25_kube-controller-manager-operator_05_serviceaccount.yaml, manifests/0000_25_kube-controller-manager-operator_06_deployment.yaml, manifests/0000_25_kube-controller-manager-operator_07_clusteroperator.yaml, manifests/0000_90_kube-controller-manager-operator_01_prometheusrole.yaml, manifests/0000_90_kube-controller-manager-operator_02_prometheusrolebinding.yaml, manifests/0000_90_kube-controller-manager-operator_03_servicemonitor.yaml, manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml, manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior
=> bug 1871890: add current profile annotations to CVO manifests

bindata/v4.1.0/kube-controller-manager/namespace-security-allocation-controller-clusterrole.yaml, pkg/operator/v411_00_assets/bindata.go
permissions for https://github.com/openshift/cluster-policy-controller/pull/39
=> Bug 1883458: add permissions for internal rangeallocation

.ci-operator.yaml
A canary for now. But the time will come for the others too :)
/cc @sttts @soltysh @marun
=> Transfer build-root control to the repository

manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
The o/k changes are in https://github.com/openshift/kubernetes/pull/415
=> Bug 1841119: Apply extendedArguments directly to kcm

bindata/v4.1.0/config/defaultconfig.yaml, pkg/operator/v411_00_assets/bindata.go
=> Bug 1898159: do not set allocate-node-cidrs, which is handled by ovn and sdn

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Follow-up to #471 which missed the bootstrap phase.
/assign @tnozicka
=> Bug 1841119: apply extendedArguments directly to kcm in bootstrap

pkg/cmd/recoverycontroller/cmd.go
=> Bug 1911211: Fix version reporting for recovery-controller

go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/OWNERS, vendor/github.com/openshift/build-machinery-go/README.md, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk, vendor/modules.txt
Pulling https://github.com/openshift/build-machinery-go/pull/30
=> Bug 1911211: Update build-machinery-go to the latest master HEAD

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
=> bug 1934132: Bump github.com/gogo/protobuf to v1.3.2

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
=> bug 1924488: Bump github.com/gogo/protobuf to v1.3.2

manifests/0000_90_kube-controller-manager-operator_04_servicemonitor-controller-manager.yaml
=> Bug 1966126: manifests: drop root_ca_cert_publisher_sync_duration_seconds metric

bindata/v4.1.0/kube-controller-manager/csr_approver_clusterrole.yaml, bindata/v4.1.0/kube-controller-manager/csr_approver_clusterrolebinding.yaml, pkg/operator/starter.go, pkg/operator/v411_00_assets/bindata.go
https://issues.redhat.com/browse/AUTH-26
This roles are required for https://github.com/openshift/cluster-policy-controller/pull/61
=> AUTH-26: CSR Approver manifests

manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
- to comply with openshift monitoring guidelines
=> Bug 2010352: add summary, description and namespace to prometheus alerts

pkg/operator/starter.go
Create a new guard controller which:
- create one guarding pod per each static operand (the guarding pod assume the operand has /readyz endpoint up and running)
- create a PDB with minAvailable when the topology is not SNO
- adjust PDB's minAvailable based on the number of master nodes available
- serves as a controller which recreates guarding pods there were deleted/terminated
=> bug 2005901: Guard controller pdb

bindata/assets/kube-controller-manager/pod.yaml
Replaces deprecated annotation with newer replacement.
/assign @soltysh
=> Bug 2035986: Replace deprecated annotation

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
To brings changes introduced in https://github.com/openshift/library-go/pull/1281
=> bug 2005901: Bump library-go

bindata/assets/config/defaultconfig.yaml, pkg/cmd/render/render_test.go
=> Bug 2040132: drop --port flag

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
To pick up https://github.com/openshift/library-go/pull/1287
/hold
Waiting until https://github.com/openshift/cluster-kube-controller-manager-operator/pull/590 gets merged.
=> bug 2005901: Sync library go

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
To bring https://github.com/openshift/library-go/pull/1296
=> bug 2044622: Sync with the latest 4.9 library-go

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
bringing in openshift/library-go#1300
=> bug 2029470: update library-go to get rapid installer pod fixes

pkg/cmd/resourcegraph/resourcegraph.go
=> Bug 1918690: update resource-graph to include current resources

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum
Replaces https://github.com/openshift/cluster-kube-controller-manager-operator/pull/595
/assign @atiratree
=> Updating ose-cluster-kube-controller-manager-operator images to be consistent with ART

test/e2e/operator_test.go
changing log level should not test network connections
We are getting 23% failure [rate](https://search.ci.openshift.org/?search=.*TestLogLevel.*&maxAge=336h&context=1&type=bug%2Bjunit&name=e2e-aws-operator&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) due to 
```
Unexpected error when reading response body: read tcp 10.128.177.24:47542->184.169.179.200:6443: read: connection reset by peer
```
=> Bug 2086959: e2e: fix flaky TestLogLevel

go.mod, manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml, pkg/operator/gcwatchercontroller/fake_prometheus_client_test.go, pkg/operator/gcwatchercontroller/gcwatcher_controller.go, pkg/operator/gcwatchercontroller/gcwatcher_controller_test.go, pkg/operator/gcwatchercontroller/prometheus_client.go, pkg/operator/starter.go
- watches important Garbage Collector alerts and degrades KCMo if they
happen
- also checks for the presence of these alerts in prometheus
supersedes #580
=> Bug 2099668: introduce GC Watcher controller and add alerts for GarbageCollector

test/e2e/operator_test.go
TestPodDisruptionBudgetAtLimitAlert https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator failing with 
```
=== RUN   TestPodDisruptionBudgetAtLimitAlert/should_alert_when_pdb_at_limit
operator_test.go:136: pods "pdbtest-njdtw" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "test" must set securityContext.seccompProfile.type to "RuntimeDefault" or …
```
=> fix TestPodDisruptionBudgetAtLimitAlert by adding SecurityContext to a pod

manifests/0000_90_kube-controller-manager-operator_05_alerts.yaml
=> [release-4.10] Bug 2114587: add runbook urls to KCM-o alerts

.ci-operator.yaml, Dockerfile.rhel7, go.mod
Needed by https://github.com/openshift/cluster-kube-controller-manager-operator/pull/656
=> Update go mod go version

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/660
=> OCPBUGS-4303: bootstrap-kube-controller-manager: specify resources.requests

bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-role.yaml, bindata/assets/kube-controller-manager/leader-election-cluster-policy-controller-rolebinding.yaml
remove unnecessary permisions and outdated comments
=> OCPBUGS-4401: limit cluster-policy-controller RBAC permissions

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/modules.txt
To get https://github.com/openshift/library-go/pull/1443.
=> Bump library-go

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
Followup to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1420
=> Drop log flags removed in k8s 1.26

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml, bindata/bootkube/manifests/secret-csr-signer-signer.yaml, bindata/bootkube/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml, go.mod, go.sum, pkg/cmd/render/render.go, vendor/github.com/openshift/library-go/pkg/assets/assets.go, vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go, vendor/github.com/openshift/library-go/pkg/operator/render/render.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/664
=> OCPBUGS-4478: Sync library go 4.12

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
This results in historical log files being wiped on restart
This reverts commit 38d70380ede2f6b7467d29cd4f9866a105517301.
=> Revert "Drop log flags removed in k8s 1.26"

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml
backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/660
=> OCPBUGS-4304: resources.requests for operator pod

bindata/bootkube/bootstrap-manifests/kube-controller-manager-pod.yaml, bindata/bootkube/manifests/secret-csr-signer-signer.yaml, bindata/bootkube/manifests/secret-initial-kube-controller-manager-service-account-private-key.yaml, go.mod, go.sum, pkg/cmd/render/render.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/664
=> OCPBUGS-4551: guard controller: set an explicit hostname to avoid name collisions

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-controller-manager-operator/pull/703
=> OCPBUGS-8235: Guard pod set readiness probe endpoint explicitly 4.10

bindata/bootkube/config/bootstrap-cluster-policy-controller-config-overrides.yaml, bindata/bootkube/config/bootstrap-config-overrides.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/686
/cc @deads2k @ibihim
=> [4.12] OCPBUGS-6789: honor feature gates during bootstrapping

OWNERS
=> OWNERS: remove ravi from the owners

bindata/assets/config/defaultconfig.yaml, pkg/cmd/render/render_test.go
=> OCPBUGS-10568: migrate to using lease objects for leader election

pkg/operator/gcwatchercontroller/gcwatcher_controller.go, pkg/operator/gcwatchercontroller/gcwatcher_controller_test.go
because we have a resync period of 5m minutes it might take this much time before the gcwatcher controller successfully connects to the prometheus API and drops KCM degraded state. This can potentially slow down the cluster installation/upgrade as shown in the jira issue.
this is an alternative solution to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/698
=> OCPBUGS-7440: do not degrade KCM when when monitoring stack rollout is in progress

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go, vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
Pulling https://github.com/openshift/library-go/pull/1546
=> OCPBUGS-15256: Sync openshift/api to reduce installerpod configmap based file permissions to 0600

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
Pulling https://github.com/openshift/library-go/pull/1574
=> OCPBUGS-16794: installerpod: change pod manifest mode to 0600

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546
=> [release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/modules.txt
=> TRT-1420: Bump openshift/library-go to pick up revision_controller revert

pkg/cmd/render/render_test.go
=> NO-JIRA: Make render unit pass consistently

.snyk
=> OCPBUGS-26117: Add .snyk file to exclude vendor and ignore unit tests

go.mod, go.sum, test/e2e/satokensigner_test.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/modules.txt
Syncing with https://github.com/openshift/library-go/pull/1682
=> WRKLDS-1071: revision_controller: do not create a new revision when a required object is missing

README.md
related to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/833
=> NO-JIRA: readme: describe mapping between operatorLogLevel and log level

Makefile
=> CNTRLPLANE-1275:Fixing arch issue

Makefile
=> OCPBUGS-61323:CNTRLPLANE-1275:Fixing arch issue
